### ISSUE TITLE
Can't find commands in command palette

### ISSUE THREAD

**Issue by Milozzy** [airtoxin/Sublime-Sound#12]
Hi!
The Command List than you provided in the README doesn't appear in my command palette, so I have no way to toggle sound, install new soundset, etc.
Except for that, the plugin works perfectly.
Any idea? ST3 on Linux here.

Thanks for your work,

regards

**Comment by airtoxin** [comment]
Hi, Milozzy.

hmm... It's a very strange.
Is there any commands menu?
<img width="811" alt="screenshot 2016-02-25 22 48 56" src="https://cloud.githubusercontent.com/assets/2460874/13321391/112136da-dc12-11e5-8782-3998275ae5e0.png">

**Comment by Milozzy** [comment]
Hi @airtoxin and thank you very much for taking the time to help.
My menu looks very different:

![schermata del 2016-02-25 20 43 52](https://cloud.githubusercontent.com/assets/864646/13332090/b1e855d8-dc00-11e5-99fa-8238497cb66d.png)

**Comment by airtoxin** [comment]
ah. 

I forgot linux releases :bomb: https://github.com/airtoxin/Sublime-Sound/releases
I'm Preparing those releases. Please wait for bit.

**Comment by Milozzy** [comment]
Perfect! 
No worries, take your time, no need to rush.

Thank you very very much for your work :)

**Comment by Milozzy** [comment]
Ping? :)

**Comment by airtoxin** [comment]
@Milozzy Pong 🎱 
released https://github.com/airtoxin/Sublime-Sound/releases

**Comment by Milozzy** [comment]
Thanks!
Sorry to bother, now I have all the options... but I can't hear any sounds anymore.
Toggle sound doesn't affect it, I tried to change soundset, reinstalling the plugin and all... but nothing seems to work. :/

Both Linux and Windows.

**Comment by airtoxin** [comment]
omg ;((
sorry for inconvenience...

I'm fixing that but it needs bit a longer time I think.
Then use old version one.

**Comment by Milozzy** [comment]
No problem, I'll wait!
Thanks for working on it ;)

**Comment by airtoxin** [comment]
@Milozzy I fixed up that bug maybe.
Could you try that branch? (put/replace its plugin sources on sublime's plugin directory)

**Comment by Milozzy** [comment]
It works!!
Both on Windows and Linux.

However, I don't know if it is related and I don't wanna be a PITA for you, but there is an issue: default soundset works perfectly, while with the other ones behave strangely. On Windows, sometimes pressing a key does not produce sound; on Linux, sometimes pressing a key produce a strange, loud and out-of-place sound that it is not part of the soundset (I played every sound separately to check.)

Thanks again!

**Comment by airtoxin** [comment]
Thank you for testing and many helps @Milozzy !

There are another bug? Sorry for inconvenience again... hmm
ok, I deal that bug on another release.

**Comment by airtoxin** [comment]
1.2.3 released https://github.com/airtoxin/Sublime-Sound/releases
