### ISSUE TITLE
How to disable keystroke sounds?

### ISSUE THREAD

**Issue by ddarbyson** [airtoxin/Sublime-Sound#7]
Hello, I'd like to disable the key stroke sounds. They can get pretty tired after every character... Is there an option for this?

**Comment by airtoxin** [comment]
yes. remove modify sounds on your soundset.
Sublime Menu > Preference > Package Settings > Sound > Add Soundset
then, open soundset directory you want suppress keystroke sound and remove or rename `on_modify` directory to `_on_modify`

**Comment by ddarbyson** [comment]
Thanks i'll try when I get home from work!

**Comment by ddarbyson** [comment]
Yup, that works for now. Would be nice to suppress this in the options configuration file. All the best!
