### ISSUE TITLE
Play sound on_save only when file is done saving

### ISSUE THREAD

**Issue by ddarbyson** [airtoxin/Sublime-Sound#9]
This is actually the main reason for downloading this plugin. I work on remote hosts quite frequently and sometimes there is a bit of latency when hitting Cmd+S to when the last Byte is done transferring.

The audible noise for on_save action would be a better indicate the file is done saving only after the file is 100% completed saving (or transfer to the remote host). 

Prior to this plugin, saving a file with latency can be quite frustrating as you need to keep refreshing the remote host to see if the file is done saving. Your plugin would solve this issue if you can make it sound after the on_save is complete.

I use Expandrive w/ Sublime Text 3.

**Comment by airtoxin** [comment]
It is hard to implement.
This plugin only knows Sublime's event and Sublime has no "upload complete" event, It's a your FTP? client's event. 
So this plugin doesn't know when upload was completed? when plays sound?

**Comment by ddarbyson** [comment]
ah, understand... this event would be nice for J Skinner to supply an api for you.
